name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install libraries
      run: sudo apt-get update && sudo apt-get install libx11-dev libxi-dev libxrandr-dev libgl1-mesa-dev libudev-dev libopenal-dev libvorbis-dev libflac-dev libxinerama-dev libxcursor-dev libboost-all-dev libfreetype-dev zlib1g-dev libssl-dev libcurl4-openssl-dev 
    
    - name: Check if SFML path exists
      run: |
        if [ ! -d "${{github.workspace}}/build/_deps/SFML" ]; then
          echo "Path does not exist"
          touch path_not_exists.txt
        else
          echo "Path exists"
        fi
    - name: Install and build SFML 2.5.1 static
      run: |
        mkdir -p ${{github.workspace}}/build/_deps/
        git clone https://github.com/SFML/SFML.git -b 2.5.x ${{github.workspace}}/build/_deps/SFML
        cmake -B ${{github.workspace}}/build/SFML/build -S ${{github.workspace}}/build/SFML -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF
        cmake --build ${{github.workspace}}/build/SFML/build --config="Release"
      if: success() && always() && !contains(run.outputs, 'Path exists')

    - name: Restore cached Dependencies
      id: cache-restore
      uses: actions/cache/restore@v3
      with:
        path: ${{ github.workspace }}/build/_deps/
        key: ${{ runner.os }}-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DSFML_ROOT=${{github.workspace}}/build/SFML/build

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Cache Dependencies
      id: cache-deps
      uses: actions/cache/save@v3
      with:
        path: ${{ github.workspace }}/build/_deps/
        key: ${{ steps.cache-restore.outputs.cache-primary-key }}

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}}

