name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - uses: actions/set-env@v1
      with:
        env_name: DEPS_PATH
        env_value: ${{github.workspace}}/build/_deps/

    - uses: actions/set-env@v1
      with:
        env_name: SFML_PATH
        env_value: ${{ env.DEPS_PATH }}/SFML
    
    - name: Install libraries
      run: sudo apt-get update && sudo apt-get install libx11-dev libxi-dev libxrandr-dev libgl1-mesa-dev libudev-dev libopenal-dev libvorbis-dev libflac-dev libxinerama-dev libxcursor-dev libboost-all-dev libfreetype-dev zlib1g-dev libssl-dev libcurl4-openssl-dev 

    - name: Restore cached Dependencies
      id: cache-restore
      uses: actions/cache/restore@v3
      with:
        path: ${{ env.DEPS_PATH }}
        key: ${{ runner.os }}-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}

    - name: Install and build SFML 2.5.1 static
      run: |
        if [ -e "${{ env.SFML_PATH }}" ]; then
          echo "SFML Path exists. Skipping SFML build"
        else
          mkdir -p ${{ env.DEPS_PATH }}
          git clone https://github.com/SFML/SFML.git -b 2.5.x ${{ env.SFML_PATH }}
          cmake -B ${{ env.SFML_PATH }}/build -S ${{ env.SFML_PATH }} -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF
          cmake --build ${{ env.SFML_PATH }}/build --config="Release"
        fi
    
    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DSFML_ROOT=${{ env.SFML_PATH }}/build

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Cache Dependencies
      id: cache-deps
      uses: actions/cache/save@v3
      with:
        path: ${{ DEPS_PATH }}
        key: ${{ steps.cache-restore.outputs.cache-primary-key }}

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}}

